services:
  server:
    build:
      context: .
    image: anum0349/dev_portfolio:v1
    environment:
      NODE_ENV: production
      DB_URI: mongodb://db:27017/portfolio # Match the MongoDB service hostname
    ports:
      - "7997:7997"
    depends_on:
      db:
        condition: service_healthy # Wait for MongoDB to be healthy
    networks:
      - app-network

  db:
    image: anum0349/mongo_db:v1
    restart: always
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
